# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

container: cypress/browsers:latest




steps:
  - script: |
      npm ci
      npm install mochawesome
    displayName: 'Installations'

  - script: |
      npx cypress run --browser chrome --reporter mochawesome --reporter-options "reportDir=mochawesome-report,reportFilename=chrome-results"
    displayName: 'Run Tests'
    continueOnError: true
  
  - publish: $(System.DefaultWorkingDirectory)/mochawesome-report
    artifact: Report
    condition: succeededOrFailed()

  - publish: $(System.DefaultWorkingDirectory)/cypress/screenshots
    artifact: Screenshots 
    condition: failed()
